build: Require c99 explicitly
It appears this is the oldest version we support – c89 fails with:

    error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode

In the future, we will bump to c11, since that will be soon required by GLib.

Also using gnu variant since we use various newer POSIX features.