fr-init.c: Fix linking
ForceDirectoryCreation was defined as a global variable in 2 separate
sources but only used in one, so remove the definition where it wasn't
used.

Fixes:
/usr/bin/ld: src/25a6634@@file-roller@exe/fr-init.c.o:(.bss+0x410): multiple definition of `ForceDirectoryCreation'; src/25a6634@@file-roller@exe/fr-application.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status